

#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
author: Glom_

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}

softdepend:
  - PlaceholderAPI
  - AttributeSystem
  - MythicMobs
